import type { Badge, CharacterItem, Lesson, LevelId, Story } from './types'
import { charData } from './utils/charData'

export const levels: Array<{ id: LevelId; title: string; description: string; color: string }> = [
  { id: 'sprout', title: '启蒙识字', description: '从身边的人和自然开始', color: '#32b67a' },
  { id: 'bridge', title: '幼小衔接', description: '把常见事物连成小句子', color: '#f5a524' },
  { id: 'grade1', title: '一年级基础', description: '校园、时间和动作词', color: '#3a86ff' },
  { id: 'grade2', title: '二年级提升', description: '更丰富的观察和表达', color: '#ef476f' },
  { id: 'grade34', title: '三四年级拓展', description: '阅读里的常用字词', color: '#7b61ff' },
  { id: 'grade56', title: '五六年级积累', description: '面向长文阅读和写作', color: '#118ab2' },
]

const makeCharacter = (
  id: string,
  char: string,
  pinyin: string,
  imageGlyph: string,
  meaning: string,
  words: string[],
  sentences: string[],
  level: LevelId,
  tags: string[],
): CharacterItem => ({
  id,
  char,
  pinyin: charData[char]?.pinyin ?? pinyin,
  imageGlyph,
  meaning,
  words,
  sentences,
  radical: tags[0] ?? '基础',
  structure: char.length === 1 ? '独体/合体识别' : '组合字形',
  strokeCount: charData[char]?.strokes ?? Math.max(1, char.codePointAt(0)! % 18),
  mistakeNote: `注意“${char}”在词语“${words[0]}”中的读音和字形。`,
  pictographHint: `${imageGlyph} -> ${char}`,
  level,
  tags,
  strokeKey: char,
})

export const characters: CharacterItem[] = [
  makeCharacter('c001', '日', 'ri', '☀', '太阳，也表示白天。', ['日出', '生日', '日子'], ['红红的太阳出来了。'], 'sprout', ['自然']),
  makeCharacter('c002', '月', 'yue', '☾', '月亮，也表示月份。', ['月亮', '月光', '一月'], ['弯弯的月亮挂在天上。'], 'sprout', ['自然']),
  makeCharacter('c003', '山', 'shan', '△', '高高的山。', ['大山', '山上', '青山'], ['小鸟飞过高高的山。'], 'sprout', ['自然']),
  makeCharacter('c004', '水', 'shui', '≈', '河流、雨水、喝的水。', ['水杯', '河水', '喝水'], ['小鱼在水里游。'], 'sprout', ['自然']),
  makeCharacter('c005', '火', 'huo', '✦', '燃烧时发光发热的东西。', ['火苗', '火车', '大火'], ['红红的火苗跳起来。'], 'sprout', ['自然']),
  makeCharacter('c006', '木', 'mu', '♣', '树木，木头。', ['木头', '树木', '木马'], ['木马在院子里。'], 'sprout', ['自然']),
  makeCharacter('c007', '人', 'ren', '人', '我们每一个人。', ['大人', '小人', '人们'], ['小人儿笑了。'], 'sprout', ['人物']),
  makeCharacter('c008', '口', 'kou', '□', '嘴巴，也像一个开口。', ['口水', '门口', '一口'], ['门口有一只小鞋。'], 'sprout', ['身体']),
  makeCharacter('c009', '手', 'shou', '✋', '用来拿东西、写字。', ['小手', '拍手', '手心'], ['我用小手拍一拍。'], 'sprout', ['身体']),
  makeCharacter('c010', '足', 'zu', '◡', '脚，也表示足够。', ['足球', '手足', '足印'], ['我们一起踢足球。'], 'sprout', ['身体']),
  makeCharacter('c011', '大', 'da', '大', '尺寸、年龄或数量多。', ['大家', '大门', '大树'], ['大树给我们遮太阳。'], 'bridge', ['形容']),
  makeCharacter('c012', '小', 'xiao', '小', '尺寸、年龄或数量少。', ['小猫', '小手', '小河'], ['小猫轻轻地走。'], 'bridge', ['形容']),
  makeCharacter('c013', '上', 'shang', '↑', '位置在高处。', ['上学', '山上', '上午'], ['我背着书包去上学。'], 'bridge', ['方位']),
  makeCharacter('c014', '下', 'xia', '↓', '位置在低处。', ['下来', '下午', '下雨'], ['下雨了，我撑开小伞。'], 'bridge', ['方位']),
  makeCharacter('c015', '中', 'zhong', '◎', '在里面或中间。', ['中间', '中国', '中心'], ['花儿开在草地中间。'], 'bridge', ['方位']),
  makeCharacter('c016', '天', 'tian', '☁', '天空，也表示一天。', ['天空', '今天', '天气'], ['今天的天空很蓝。'], 'bridge', ['自然']),
  makeCharacter('c017', '田', 'tian', '▦', '种庄稼的地方。', ['田地', '水田', '田野'], ['田野里有金黄的稻子。'], 'bridge', ['自然']),
  makeCharacter('c018', '禾', 'he', '⌇', '谷类植物。', ['禾苗', '禾田'], ['禾苗在风里点头。'], 'bridge', ['自然']),
  makeCharacter('c019', '云', 'yun', '☁', '天空中的云朵。', ['白云', '云朵', '乌云'], ['白云像软软的棉花。'], 'bridge', ['自然']),
  makeCharacter('c020', '雨', 'yu', '⋮', '从云里落下来的水。', ['雨点', '下雨', '雨伞'], ['雨点落在窗户上。'], 'bridge', ['自然']),
  makeCharacter('c021', '花', 'hua', '✿', '植物开的花。', ['小花', '花朵', '红花'], ['小花在阳光下开放。'], 'grade1', ['植物']),
  makeCharacter('c022', '草', 'cao', '♧', '地上绿色的小植物。', ['小草', '草地', '青草'], ['小草从泥土里钻出来。'], 'grade1', ['植物']),
  makeCharacter('c023', '虫', 'chong', '≈', '小昆虫。', ['小虫', '虫子', '飞虫'], ['小虫躲在叶子后面。'], 'grade1', ['动物']),
  makeCharacter('c024', '鸟', 'niao', '♩', '会飞的动物。', ['小鸟', '飞鸟', '鸟叫'], ['小鸟在树上唱歌。'], 'grade1', ['动物']),
  makeCharacter('c025', '鱼', 'yu', '><>', '生活在水里的动物。', ['小鱼', '鱼儿', '鱼水'], ['小鱼摇着尾巴游走了。'], 'grade1', ['动物']),
  makeCharacter('c026', '马', 'ma', '♞', '跑得很快的动物。', ['小马', '木马', '马路'], ['小马跑过草地。'], 'grade1', ['动物']),
  makeCharacter('c027', '羊', 'yang', '♈', '爱吃草的动物。', ['小羊', '山羊', '羊毛'], ['小羊在草地上吃草。'], 'grade1', ['动物']),
  makeCharacter('c028', '牛', 'niu', '♉', '力气大的动物。', ['小牛', '黄牛', '牛奶'], ['小牛慢慢走回家。'], 'grade1', ['动物']),
  makeCharacter('c029', '子', 'zi', '子', '孩子，也可表示小的东西。', ['孩子', '儿子', '种子'], ['种子睡在泥土里。'], 'grade1', ['人物']),
  makeCharacter('c030', '女', 'nv', '女', '女孩、女性。', ['女孩', '女儿', '女子'], ['女孩把花送给妈妈。'], 'grade1', ['人物']),
  makeCharacter('c031', '学', 'xue', '✎', '学习新本领。', ['学习', '学校', '同学'], ['我们在学校学习。'], 'grade2', ['校园']),
  makeCharacter('c032', '校', 'xiao', '⌂', '学校。', ['学校', '校园', '校门'], ['校门口有一排小树。'], 'grade2', ['校园']),
  makeCharacter('c033', '书', 'shu', '▤', '装订起来供阅读的本子。', ['书包', '看书', '图书'], ['我喜欢看有图画的书。'], 'grade2', ['校园']),
  makeCharacter('c034', '文', 'wen', '文', '文字、文章。', ['文字', '语文', '课文'], ['课文里有新朋友。'], 'grade2', ['校园']),
  makeCharacter('c035', '早', 'zao', '☀', '早晨，时间靠前。', ['早上', '早安', '早读'], ['早上我对老师说早安。'], 'grade2', ['时间']),
  makeCharacter('c036', '晚', 'wan', '☾', '晚上，时间靠后。', ['晚上', '晚安', '晚会'], ['晚上月亮出来了。'], 'grade2', ['时间']),
  makeCharacter('c037', '明', 'ming', '☀☾', '明亮、清楚。', ['明天', '明亮', '说明'], ['明天我们去看花。'], 'grade2', ['时间']),
  makeCharacter('c038', '星', 'xing', '✶', '夜空里的星星。', ['星星', '星光', '红星'], ['星星在夜空里眨眼。'], 'grade2', ['自然']),
  makeCharacter('c039', '朋', 'peng', '月月', '朋友的朋。', ['朋友', '亲朋'], ['朋友一起做游戏。'], 'grade2', ['关系']),
  makeCharacter('c040', '友', 'you', '友', '友好、朋友。', ['朋友', '友好', '好友'], ['我和朋友一起读故事。'], 'grade2', ['关系']),
  makeCharacter('c041', '观', 'guan', '目', '仔细看，也表示看法。', ['观察', '观看', '观点'], ['我们观察叶子的形状。'], 'grade34', ['阅读']),
  makeCharacter('c042', '察', 'cha', '宀', '仔细看清楚。', ['观察', '察看', '明察'], ['细心观察能发现新的线索。'], 'grade34', ['阅读']),
  makeCharacter('c043', '然', 'ran', '灬', '表示样子，也常用于自然。', ['自然', '忽然', '然后'], ['忽然，一阵风吹过树林。'], 'grade34', ['表达']),
  makeCharacter('c044', '映', 'ying', '日', '照射、显现。', ['倒映', '映照', '反映'], ['湖水倒映着蓝天。'], 'grade34', ['阅读']),
  makeCharacter('c045', '感', 'gan', '心', '心里受到触动。', ['感受', '感谢', '感动'], ['我感受到春天的温暖。'], 'grade34', ['表达']),
  makeCharacter('c046', '想', 'xiang', '心', '思考、希望。', ['想象', '思想', '梦想'], ['他展开想象，写下故事。'], 'grade34', ['表达']),
  makeCharacter('c047', '诚', 'cheng', '讠', '真实、不虚假。', ['诚实', '真诚', '诚信'], ['诚实让朋友更信任你。'], 'grade56', ['品格']),
  makeCharacter('c048', '责', 'ze', '贝', '应该承担的事。', ['责任', '负责', '责备'], ['每个人都要学会负责。'], 'grade56', ['品格']),
  makeCharacter('c049', '辩', 'bian', '辛', '说明是非或不同看法。', ['辩论', '分辩', '争辩'], ['课堂上，同学们展开辩论。'], 'grade56', ['思辨']),
  makeCharacter('c050', '析', 'xi', '木', '分开来看，仔细研究。', ['分析', '解析', '剖析'], ['读文章时要学会分析原因。'], 'grade56', ['思辨']),
  makeCharacter('c051', '毅', 'yi', '殳', '坚定、不轻易放弃。', ['毅力', '坚毅', '毅然'], ['坚持练习需要毅力。'], 'grade56', ['品格']),
  makeCharacter('c052', '慧', 'hui', '心', '聪明、有智慧。', ['智慧', '聪慧', '慧心'], ['阅读让人增长智慧。'], 'grade56', ['素养']),
]

export const lessons: Lesson[] = [
  { id: 'l001', title: '太阳醒来了', subtitle: '认识自然里的第一批字', level: 'sprout', characterIds: ['c001', 'c002', 'c003', 'c004'], gameTypes: ['image-choice', 'audio-choice', 'pinyin-match'], unlockRules: {}, storyId: 's001' },
  { id: 'l002', title: '小手去探险', subtitle: '认识身体和身边事物', level: 'sprout', characterIds: ['c005', 'c006', 'c007', 'c008', 'c009'], gameTypes: ['image-choice', 'audio-choice', 'story-find'], unlockRules: { requiredLessonId: 'l001', minStars: 1 }, storyId: 's002' },
  { id: 'l003', title: '上下左右找朋友', subtitle: '学会描述位置和大小', level: 'bridge', characterIds: ['c010', 'c011', 'c012', 'c013', 'c014'], gameTypes: ['image-choice', 'pinyin-match', 'story-find'], unlockRules: { requiredLessonId: 'l002', minStars: 1 }, storyId: 's003' },
  { id: 'l004', title: '云朵和雨点', subtitle: '发现天气和田野', level: 'bridge', characterIds: ['c015', 'c016', 'c017', 'c018', 'c019', 'c020'], gameTypes: ['image-choice', 'audio-choice', 'story-find'], unlockRules: { requiredLessonId: 'l003', minStars: 1 }, storyId: 's004' },
  { id: 'l005', title: '花草动物会说话', subtitle: '在草地上认识小动物', level: 'grade1', characterIds: ['c021', 'c022', 'c023', 'c024', 'c025'], gameTypes: ['image-choice', 'audio-choice', 'pinyin-match'], unlockRules: { requiredLessonId: 'l004', minStars: 1 }, storyId: 's005' },
  { id: 'l006', title: '牧场里的早晨', subtitle: '认识更多动物朋友', level: 'grade1', characterIds: ['c026', 'c027', 'c028', 'c029', 'c030'], gameTypes: ['image-choice', 'pinyin-match', 'story-find'], unlockRules: { requiredLessonId: 'l005', minStars: 1 }, storyId: 's006' },
  { id: 'l007', title: '去学校啦', subtitle: '走进校园和课堂', level: 'grade2', characterIds: ['c031', 'c032', 'c033', 'c034', 'c035'], gameTypes: ['image-choice', 'audio-choice', 'story-find'], unlockRules: { requiredLessonId: 'l006', minStars: 1 }, storyId: 's007' },
  { id: 'l008', title: '星光朋友会', subtitle: '读懂时间和朋友', level: 'grade2', characterIds: ['c036', 'c037', 'c038', 'c039', 'c040'], gameTypes: ['audio-choice', 'pinyin-match', 'story-find'], unlockRules: { requiredLessonId: 'l007', minStars: 1 }, storyId: 's008' },
  { id: 'l009', title: '观察小世界', subtitle: '三四年级阅读观察词', level: 'grade34', characterIds: ['c041', 'c042', 'c043', 'c044', 'c045', 'c046'], gameTypes: ['pinyin-match', 'story-find', 'image-choice'], unlockRules: { requiredLessonId: 'l008', minStars: 1 }, storyId: 's009' },
  { id: 'l010', title: '思辨成长课', subtitle: '五六年级表达与品格词', level: 'grade56', characterIds: ['c047', 'c048', 'c049', 'c050', 'c051', 'c052'], gameTypes: ['pinyin-match', 'audio-choice', 'story-find'], unlockRules: { requiredLessonId: 'l009', minStars: 1 }, storyId: 's010' },
]

export const stories: Story[] = [
  { id: 's001', title: '太阳和月亮', level: 'sprout', text: '早上，太阳从山后面升起来，天空亮了。河水闪着光，好像在跟太阳说早安。到了晚上，月亮悄悄爬上树梢，轻轻地照着大地。', highlightCharacterIds: ['c001', 'c002', 'c003', 'c004'], unlockAfterLessonIds: ['l001'] },
  { id: 's002', title: '小人儿拍手', level: 'sprout', text: '火苗旁边有木马。小人儿张开口，伸出手，开心地笑。', highlightCharacterIds: ['c005', 'c006', 'c007', 'c008', 'c009'], unlockAfterLessonIds: ['l002'] },
  { id: 's003', title: '小脚上山', level: 'bridge', text: '小足印来到大山下。小朋友往上走，又从山上下来看小花。', highlightCharacterIds: ['c010', 'c011', 'c012', 'c013', 'c014'], unlockAfterLessonIds: ['l003'] },
  { id: 's004', title: '云雨到田里', level: 'bridge', text: '蓝蓝的天空飘来一朵朵白云，云朵越聚越多，慢慢地变成了灰色。哗啦哗啦，雨点落下来了！田里的禾苗仰起头，咕咚咕咚喝饱了雨水，开心地挺直了腰。', highlightCharacterIds: ['c015', 'c016', 'c017', 'c018', 'c019', 'c020'], unlockAfterLessonIds: ['l004'] },
  { id: 's005', title: '草地音乐会', level: 'grade1', text: '春天来了，花儿一朵一朵地开了，草地也变得绿油油的。小虫子趴在叶子上，小鸟站在树枝上，小鱼探出水面，大家都竖起耳朵，听风儿轻轻地唱起了歌。', highlightCharacterIds: ['c021', 'c022', 'c023', 'c024', 'c025'], unlockAfterLessonIds: ['l005'] },
  { id: 's006', title: '牧场早饭', level: 'grade1', text: '小马跑来，小羊吃草，小牛喝奶。孩子和女孩一起数动物。', highlightCharacterIds: ['c026', 'c027', 'c028', 'c029', 'c030'], unlockAfterLessonIds: ['l006'] },
  { id: 's007', title: '校门口的早安', level: 'grade2', text: '早晨的阳光照在校门口，同学们背着书包高高兴兴地走进学校。上课铃响了，语文老师带着大家一起朗读课文，教室里传出整齐又响亮的读书声。', highlightCharacterIds: ['c031', 'c032', 'c033', 'c034', 'c035'], unlockAfterLessonIds: ['l007'] },
  { id: 's008', title: '星光朋友会', level: 'grade2', text: '夜幕降临了，一颗颗明亮的星星挂在天上，像在眨眼睛。朋友们围坐在草地上，你一句我一句，讲着关于友谊的温暖小故事，笑声飘得很远很远。', highlightCharacterIds: ['c036', 'c037', 'c038', 'c039', 'c040'], unlockAfterLessonIds: ['l008'] },
  { id: 's009', title: '湖边观察记', level: 'grade34', text: '我们静静地坐在湖边，观察着周围的自然变化。柳树的枝条轻轻拂过水面，树影倒映在湖中，像一幅会动的画。微风吹来，湖面泛起一圈圈波纹，让人心里感到格外宁静。', highlightCharacterIds: ['c041', 'c042', 'c043', 'c044', 'c045', 'c046'], unlockAfterLessonIds: ['l009'] },
  { id: 's010', title: '班级辩论会', level: 'grade56', text: '今天的班会上，大家围绕"小学生要不要多读课外书"展开了热烈的辩论。正方同学引经据典，反方同学也不甘示弱。每个发言的同学都认真负责地表达自己的观点，分析问题时既充满智慧又坚持不懈，赢得了阵阵掌声。', highlightCharacterIds: ['c047', 'c048', 'c049', 'c050', 'c051', 'c052'], unlockAfterLessonIds: ['l010'] },
]

export const badges: Badge[] = [
  { id: 'first_lesson', title: '第一颗星', description: '完成第一个识字关卡', icon: '★' },
  { id: 'ten_chars', title: '十字小达人', description: '认识 10 个汉字', icon: '十' },
  { id: 'twenty_chars', title: '故事探险家', description: '认识 20 个汉字', icon: '书' },
  { id: 'five_stories', title: '故事收藏家', description: '解锁 5 个故事', icon: '本' },
  { id: 'grade34_ready', title: '阅读观察员', description: '认识 40 个汉字，进入三四年级拓展', icon: '观' },
  { id: 'grade56_ready', title: '思辨小学者', description: '认识 50 个汉字，进入五六年级积累', icon: '慧' },
  { id: 'all_lessons', title: '星光毕业礼', description: '完成全部 MVP 关卡', icon: '冠' },
]

export const sentenceTemplates = [
  '我看见了{word}。',
  '{word}在{place}。',
  '今天，{word}和我一起玩。',
  '我喜欢{word}，也喜欢读故事。',
]
